### ISSUE TITLE
CANNON HIGHLIGHTER NOT WORKING FOR ORNAMENT

### ISSUE THREAD

**Issue by WiggleNibble** [ConorLeckey/Cannon-Highlighter#6]
Cannon Highlighter not working. No hit zones showing.

Edit: Not working if you have a cannon ornament. but working if you remove it.

![image](https://user-images.githubusercontent.com/110086391/201013750-e467b8dc-ee04-4184-aca2-611ef446cf69.png)

**Comment by rsbelza** [comment]
yes it's not working on my end too. please make it work

**Comment by ConorLeckey** [comment]
Fixed in https://github.com/ConorLeckey/Cannon-Highlighter/pull/8

Will mark this as resolved, changes will take effect as soon as update is approved by runelite.
